[[redirects]]   
  from = "/events/*"
  to = "/posts"

[[redirects]]   
  from = "/partners"
  to = "/membership"

[[redirects]]   
  from = "/join"
  to = "/membership"

[[redirects]]   
  from = "/donate"
  to = "/membership"
  
[[redirects]] 
  from = "/facebook"
  to = "https://www.facebook.com/Hackerspace-Pomorze-103254931521373/"
  
[[redirects]]   
  from = "/twitter"
  to = "https://twitter.com/hspsh"
  
[[redirects]]   
  from = "/github"
  to = "https://github.com/hspsh"

